### PR TITLE
fix: missed event of checkbox :ambulance: #291

### LINKED ISSUE #291: Improve tests in checkbox

### PR DESCRIPTION
**Pull request by iurynogueira**
fix #291

### CODE REVIEW

**Review by lucasrasec — APPROVED** [review]

File: projects/ion/src/lib/checkbox/checkbox.component.ts [hunk 1]
```diff
@@ -35,7 +35,7 @@ const stateChange = {
   templateUrl: './checkbox.component.html',
   styleUrls: ['./checkbox.component.scss'],
 })
-export class CheckboxComponent implements AfterViewInit, OnChanges {
+export class CheckboxComponent implements AfterViewInit {
```
Comment (Thiago-Pio-Brisanet) [inline projects/ion/src/lib/checkbox/checkbox.component.ts:37]: Onchanges ainda sendo importado na linha 7!
image

**Review by Thiago-Pio-Brisanet — APPROVED** [review]
